### ISSUE TITLE
Add page to wiki about bash scripts

### ISSUE THREAD

**Issue by JuliaGreenberg1** [urban-displacement/UDP-template#5]
@hmooreo Explain:

- [x] how to check on jobs through [this link](https://eml.berkeley.edu/monitoring)
- [x] how to create helper & submitter bash scripts, pass in arguments in R script, create for-loops, etc.
- [x] how to run the bash scripts, which folder to run them from, etc. (navigate to folder the `.sh` file is located in, then type `bash join_mig_submitter.sh` into the terminal)
- [x] can make sure job was submitted by entering `squeue`
- [x] how to print statements like "Starting..." and "This took x amount of time" and read the output with `cat slurm-[job_id].out`
- [x] how to automate cancelling a job if one of them fails (`scancel [job_id -- # only]`). NOTE: you'll never be able to cancel a job submitted by another user, BUT if you're using the UDP server you might do this accidentally (but it's very unlikely)
- [x] give a specific example!
- [x] how to run a job that requires a lot of memory: https://eml.berkeley.edu/cluster#bigmem
- [x] how to run manually - for example: `sbatch -C mem768g join_mig_submitter.sh [year]` (if I need a lot of memory)

**Comment by hcplusplus** [comment]
completed TODOs on wiki page
